version: '3.9'
services:
  db:
    image: mysql:8
    container_name: project-pets-db
    environment:
      - MYSQL_ROOT_PASSWORD=123456789
      - MYSQL_DATABASE=dbprojectpets
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin123
    # Montamos un volumen persistente para /var/lib/mysql
    volumes:
      - db_data:/var/lib/mysql
      - ./project-pets-database/init-scripts:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
  backend:
    build:
      context: ./project-pets-backend
      dockerfile: Dockerfile
    container_name: project-pets-backend
    environment:
      # Config BD. 'db' es el nombre del servicio anterior
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/dbprojectpets?useSSL=false&allowPublicKeyRetrieval=true
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=admin123
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none
      # etc
    depends_on:
      - db
    ports:
      - "8080:8080"

  frontend:
    build:
      context: ./project-pets-frontend
      dockerfile: Dockerfile
    container_name: project-pets-frontend
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  db_data: